# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: xdaliclock for the Tandy/TRS-80 Color Computer
email: jamieleecho at gmail dot com
description: > # this means to ignore newlines until "baseurl:"
  A Color Computer port of Jamie Zawinsk's xdaliclock.
baseurl: "/xdaliclock" # the subpath of your site, e.g. /blog
url: "http://jamieleecho.github.io" # the base hostname & protocol for your site
github_username:  jamieleecho

# Build settings
markdown: kramdown
